# .cargo/config.toml

# Windows MSVC - bruk dynamisk CRT (FLTK forventer dette)
[target.x86_64-pc-windows-msvc]
# Bruker standard dynamisk CRT

[target.i686-pc-windows-msvc]
# Bruker standard dynamisk CRT

[target.aarch64-pc-windows-msvc]
# Bruker standard dynamisk CRT

# Linux - bruk system linker (gcc) og legg til library paths
[target.x86_64-unknown-linux-gnu]
linker = "gcc"
rustflags = [
    "-L", "/usr/lib/x86_64-linux-gnu",
    "-L", "/usr/lib",
    "-L", "/lib/x86_64-linux-gnu",
]

# Linux - statisk linking med musl
[target.x86_64-unknown-linux-musl]
rustflags = ["-C", "target-feature=+crt-static"]

[target.aarch64-unknown-linux-musl]
rustflags = ["-C", "target-feature=+crt-static"]

# macOS - statisk der det er mulig
[target.x86_64-apple-darwin]
rustflags = ["-C", "target-feature=+crt-static"]

[target.aarch64-apple-darwin]
rustflags = ["-C", "target-feature=+crt-static"]
