# .cargo/config.toml

# Windows MSVC - use dynamic CRT (FLTK expects this)
[target.x86_64-pc-windows-msvc]
# Uses standard dynamic CRT

[target.i686-pc-windows-msvc]
# Uses standard dynamic CRT

[target.aarch64-pc-windows-msvc]
# Uses standard dynamic CRT

# Linux - use system linker (gcc) and add library paths
[target.x86_64-unknown-linux-gnu]
linker = "gcc"
rustflags = [
    "-L", "/usr/lib/x86_64-linux-gnu",
    "-L", "/usr/lib",
    "-L", "/lib/x86_64-linux-gnu",
]

# Linux - static linking with musl
[target.x86_64-unknown-linux-musl]
rustflags = ["-C", "target-feature=+crt-static"]

[target.aarch64-unknown-linux-musl]
rustflags = ["-C", "target-feature=+crt-static"]

# macOS - static where possible
[target.x86_64-apple-darwin]
rustflags = ["-C", "target-feature=+crt-static"]

[target.aarch64-apple-darwin]
rustflags = ["-C", "target-feature=+crt-static"]
